import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import pkg from "../package.json";
import manifest from "../extension/manifest.json";

const ROOT = join(import.meta.dir, "..");
const BUNDLE = join(ROOT, "extension/devbar.cdn.js");
const background = readFileSync(join(ROOT, "extension/background.js"), "utf-8");

describe("chrome extension", () => {
	test("manifest version tracks the package version", () => {
		// bump.config.ts bumps both; this catches them drifting apart.
		expect(manifest.version).toBe(pkg.version);
	});

	// MV3 bans remotely hosted code, and a page CSP can block an injected
	// <script src>. The bundle must be a file inside the extension.
	test("injects no remote code", () => {
		expect(background).not.toMatch(/https?:\/\/[^"']+\.js/);
		expect(background).toContain("devbar.cdn.js");
		expect(manifest.web_accessible_resources[0]?.resources).toContain("devbar.cdn.js");
	});

	// React fiber expandos are invisible from an isolated world, so element
	// capture would silently lose component context.
	test("injects into the MAIN world", () => {
		expect(background).toContain('world: "MAIN"');
		expect(background).not.toMatch(/world:\s*"ISOLATED"/);
		// world + files injection needs Chrome 111.
		expect(manifest.minimum_chrome_version).toBe("111");
	});

	test("declares the permissions injection needs", () => {
		expect(manifest.permissions).toContain("scripting");
		expect(manifest.permissions).toContain("activeTab");
	});

	test("the shipped bundle defines window.Devbar", () => {
		if (!existsSync(BUNDLE)) return; // generated by `bun run build:extension`
		const bundle = readFileSync(BUNDLE, "utf-8");
		expect(bundle).toContain("window.Devbar=");
		expect(bundle.length).toBeGreaterThan(100_000);
	});

	test("the bundle is published with the package", () => {
		expect(pkg.files).toContain("extension/devbar.cdn.js");
	});
});
